# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cancha', models.CharField(max_length=30, verbose_name='Nombre')),
                ('direccion_cancha', models.CharField(max_length=60, verbose_name='Direccion')),
            ],
            options={
                'db_table': 'cancha',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=30, verbose_name='Nombre del Equipo')),
                ('categoria_equipo', models.SmallIntegerField(choices=[(1, 'Categoria A'), (2, 'Categoria B'), (3, 'Categoria C')])),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.SmallIntegerField(choices=[(1, 'Marcacion del gol'), (2, 'Falta'), (3, 'Tarjeta amarilla'), (4, 'Tarjeta azul'), (5, 'Tarjeta roja'), (6, 'Cambio de jugador')])),
                ('hora_evento', models.TimeField()),
                ('jugador', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eventos_partido',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=12, verbose_name='Identificacion')),
                ('tipo_identifcacion', models.SmallIntegerField(choices=[(1, 'T.I'), (2, 'C.C'), (3, 'C.E')])),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('perfil', models.CharField(max_length=60, verbose_name='Perfil del jugador')),
                ('sexo', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')])),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.Equipo')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jugador',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_partido', models.SmallIntegerField(choices=[(1, 'Amistoso')])),
                ('resultado', models.CharField(max_length=30, verbose_name='Resultado')),
                ('estado_partido', models.SmallIntegerField(choices=[(1, 'No iniciado'), (2, 'En proceso'), (3, 'Finalizado')])),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Cancha')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_1', to='inicio.Equipo')),
                ('visitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_2', to='inicio.Equipo')),
            ],
            options={
                'db_table': 'partido',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(auto_now=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('abono', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado_reserva', models.SmallIntegerField(choices=[(1, 'Reservado'), (2, 'Disponible')])),
                ('cancha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.Cancha')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_torneo', models.SmallIntegerField(choices=[(1, 'T.relampago'), (2, 'Campeonato')], null=True)),
                ('nombre_torneo', models.CharField(max_length=30, verbose_name='Nombre torneo')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('premio', models.TextField(max_length=100, verbose_name='Premios')),
                ('estado_torneo', models.SmallIntegerField(choices=[(1, 'No iniciado'), (2, 'En proceso'), (3, 'Finalizado')])),
                ('partido', models.ManyToManyField(to='inicio.Partido')),
            ],
            options={
                'db_table': 'torneo',
            },
        ),
        migrations.AddField(
            model_name='eventopartido',
            name='partido',
            field=models.ManyToManyField(to='inicio.Partido'),
        ),
    ]
