# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Cancha'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(),
        ),
    ]
